<a href="https://colab.research.google.com/github/eunjung1005/jejumaster/blob/main/%EC%83%81%ED%92%88%EA%B6%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
PATH = './sample_data/'
FILE = '온누리상품권.csv'

In [40]:
!sudo apt-get install -y fonts-nanum #리눅스명령(수도)
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [1]:
import pandas  as pd
import numpy as np
import matplotlib as plt
print(pd.__version__)
print(np.__version__)
print(plt.__version__)

1.5.3
1.23.5
3.7.1

데이터다운로드 집어넣기

In [22]:
import pandas as pd
PATH = './sample_data/'
FILE = '온누리상품권.csv'
file = PATH+FILE
df = pd.read_csv(file, encoding = 'cp949') #cp949: 윈도우OS 기본 인코딩 포맷
df.head(3)

,구분(단위_천원),2010년,2011년,2012년,2013년,2014년,2015년 1분기,2015년 2분기,2015년 3분기,2015년 4분기,...,2016년 3분기,2016년 4분기,2017년 1분기,2017년 2분기,2017년 3분기,2017년 4분기,2018년 1분기,2018년 2분기,2018년 3분기,2018년 4분기
0,강원,858900.0,3094710.0,5975830,6362605,8456720,2418110,2009760,11232622,5503255,...,5346285,6325379,7162135,3964170,6407205,6037319,6370970,2255039,3520549,3174705
1,경기,9148785.0,54602880.0,135103950,72342730,57094890,25258780,7664395,51939475,16501540,...,35939260,34421255,32379700,16477150,32913355,21238100,72094880,19876534,46210663,20080097
2,경남,4472580.0,8089965.0,25849940,16489250,23418575,6356530,6008700,25442470,13093700,...,15915315,13834635,22987455,16192210,23320955,18259825,44294062,15942300,29744584,25541148

In [23]:
df.columns

Index(['구분(단위_천원)', '2010년', '2011년', '2012년', '2013년', '2014년', '2015년 1분기',
       '2015년 2분기', '2015년 3분기', '2015년 4분기', '2016년 1분기', '2016년 2분기',
       '2016년 3분기', '2016년 4분기', '2017년 1분기', '2017년 2분기', '2017년 3분기',
       '2017년 4분기', '2018년 1분기', '2018년 2분기', '2018년 3분기', '2018년 4분기'],
      dtype='object')

In [24]:
# df.drop( '2013년',axis=1, inplace=True)
# df.drop( '2014년',axis=1, inplace=True)
df.drop( '2015년 1분기',axis=1, inplace=True)
df.drop( '2015년 2분기',axis=1, inplace=True)
df.drop( '2015년 3분기',axis=1, inplace=True)
df.drop( '2015년 4분기',axis=1, inplace=True)
df.drop( '2016년 1분기',axis=1, inplace=True)
df.drop( '2016년 2분기',axis=1, inplace=True)
df.drop( '2016년 3분기',axis=1, inplace=True)

df.drop( '2016년 4분기',axis=1, inplace=True)
df.drop( '2017년 1분기',axis=1, inplace=True)
df.drop( '2017년 2분기',axis=1, inplace=True)
df.drop( '2017년 3분기',axis=1, inplace=True)
df.drop( '2017년 4분기',axis=1, inplace=True)
df.drop( '2018년 1분기',axis=1, inplace=True)
df.drop( '2018년 2분기',axis=1, inplace=True)
df.drop( '2018년 3분기',axis=1, inplace=True)
df.drop( '2018년 4분기',axis=1, inplace=True)

df

   구분(단위_천원)       2010년       2011년      2012년     2013년      2014년
0         강원    858900.0   3094710.0    5975830   6362605    8456720
1         경기   9148785.0  54602880.0  135103950  72342730   57094890
2         경남   4472580.0   8089965.0   25849940  16489250   23418575
3         경북   2499550.0   4643210.0   19148825  13012435   17889815
4         광주   1313975.0   3656770.0    5197015   7208855   16506755
5         대구   3088175.0   6575530.0    9932165  10975015   36656900
6         대전   3496785.0   5581650.0    8682380   8781735   15029815
7         부산   7168350.0  12768100.0   16010120  13012755   39729485
8         서울  14210590.0  53672870.0   89844870  88785150  143279070
9         울산   1855785.0   5072680.0   15012690  19202260   24854565
10        인천    943220.0   7580260.0    9839420   7558630   14917645
11        전남  11611745.0  28117505.0   33491540  10016890   19513270
12        전북  11231405.0  19420750.0   27234845  18017360   28149925
13        제주    366935.0   2487105.0    3731415   1569170    4391790
14        충남   1309660.0   4012105.0    9874605  11739800   10421475
15        충북   1757865.0   3056070.0    4518225   4990525    8163485
16        세종         NaN         NaN     151650   1022535    1956860

In [25]:
df.columns

Index(['구분(단위_천원)', '2010년', '2011년', '2012년', '2013년', '2014년'], dtype='object')

In [27]:
df.columns = ['지역명', '2010년', '2011년', '2012년', '2013년', '2014년']
df.columns

Index(['지역명', '2010년', '2011년', '2012년', '2013년', '2014년'], dtype='object')

In [28]:
df[df['지역명'].str.contains('제주')]

df

   지역명       2010년       2011년      2012년     2013년      2014년
0   강원    858900.0   3094710.0    5975830   6362605    8456720
1   경기   9148785.0  54602880.0  135103950  72342730   57094890
2   경남   4472580.0   8089965.0   25849940  16489250   23418575
3   경북   2499550.0   4643210.0   19148825  13012435   17889815
4   광주   1313975.0   3656770.0    5197015   7208855   16506755
5   대구   3088175.0   6575530.0    9932165  10975015   36656900
6   대전   3496785.0   5581650.0    8682380   8781735   15029815
7   부산   7168350.0  12768100.0   16010120  13012755   39729485
8   서울  14210590.0  53672870.0   89844870  88785150  143279070
9   울산   1855785.0   5072680.0   15012690  19202260   24854565
10  인천    943220.0   7580260.0    9839420   7558630   14917645
11  전남  11611745.0  28117505.0   33491540  10016890   19513270
12  전북  11231405.0  19420750.0   27234845  18017360   28149925
13  제주    366935.0   2487105.0    3731415   1569170    4391790
14  충남   1309660.0   4012105.0    9874605  11739800   10421475
15  충북   1757865.0   3056070.0    4518225   4990525    8163485
16  세종         NaN         NaN     151650   1022535    1956860

In [35]:
df_total_group=df[df['지역명'].str.contains('제주')]
df_total_group

   지역명     2010년      2011년    2012년    2013년    2014년
13  제주  366935.0  2487105.0  3731415  1569170  4391790

In [33]:
df_total_group.columns

Index(['지역명', '2010년', '2011년', '2012년', '2013년', '2014년'], dtype='object')

In [38]:
import matplotlib.pyplot as plt

# 코랩에서 한글 폰트 설치한 후 사용하기!!!
# plt.rc('font', family='cmb10')                  # (코랩)한글 폰트
plt.rc('font', family='NanumBarunGothic')       # (코랩)한글 폰트
# plt.rc('font', family='Malgun Gothic')          # (win)한글 폰트


# 1.그래프 데이터 지정하기(X축, Y축)
x = df_total_group.['2010년', '2011년', '2012년', '2013년', '2014년']    # 지역명
y = df_total_group['지역명']   # 인구수

# 2.그래프 그리기
plt.bar(x, y,color='k')

# 3. 그래프 꾸미기
# plt.title('대한민국 "구씨"를 찾아라') # 그래프 제목
plt.title('Find Familyname Goo!!! ') # 그래프 제목
plt.xlabel('지역')                    # x축 이름
plt.ylabel('인구수')                  # y축 이름
plt.xticks(rotation = 45)             # X축 레이블 회전
plt.show()                            # 그래프 출력하기

SyntaxError: ignored

In [19]:
import matplotlib.pyplot as plt

# 코랩에서 한글 폰트 설치한 후 사용하기!!!
# plt.rc('font', family='cmb10')                  # (코랩)한글 폰트
plt.rc('font', family='NanumBarunGothic')       # (코랩)한글 폰트
# plt.rc('font', family='Malgun Gothic')          # (win)한글 폰트
# 1. 그래프 데이터 지정하기 (X축, Y축)
#
x = [
'2017년 1분기', '2017년 2분기', '2017년 3분기', '2017년 4분기', '2018년 1분기', '2018년 2분기', '2018년 3분기', '2018년 4분기']
y = df_total_group['지역명']

# 2. 그래프 그리기
plt.figure(figsize=(12, 6))
plt.bar(x, y, color='k')

# 3. 그래프 꾸미기
plt.title('Find Familyname Goo!!!') # 그래프 제목
plt.xlabel('지역')                    # x축 이름
plt.ylabel('인구수')                  # y축 이름
plt.xticks(rotation=45)             # X축 레이블 회전
plt.show()                            # 그래프 출력하

SyntaxError: ignored